name: Trigger auto deployment for mens

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mens-AutoDeployTrigger-be6e950d-28f6-408d-84cd-fe06f3e8ef67.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: doker.io
          username: ${{ secrets.MENS_REGISTRY_USERNAME }}
          password: ${{ secrets.MENS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: doker.io/tuban/mens:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MENS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mens -g tuban-container-apps --server doker.io --username  ${{ secrets.MENS_REGISTRY_USERNAME }} --password ${{ secrets.MENS_REGISTRY_PASSWORD }}
            az containerapp update -n mens -g tuban-container-apps --image doker.io/tuban/mens:${{ github.sha }}
