name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tuban/dmens'
      - name: npm install (ci) ===================
      - run: npm ci
      - name: create folder ts-output, compile typescrept to ts-output folder and move ts-output content to main directory for production
        run: |
         mkdir ./ts-output
         npm run tsc
         sleep 2
         mv  ./ts-output/ ./
      - name: finally publish to npm registry ===================
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS }}