name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tuban/dmens'
      - name: run npm install (ci) ===================
        run: npm ci
      - name: create folder dmens if not existed
        run: mkdir -p ./dmens     
      - name: compile typescrept to dmens folder 
        run: npm run tsc
      - name: delete some folder
        run: |
         rm -rf  ./dev-client
         rm   ./create-env-file.sh
      - name: run publish to npm registery
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS }}